[package]
name = "rustcbuildx"
version = "0.1.0"
authors = ["Pierre Fenoll <pierrefenoll@gmail.com>"]
categories = [
	"caching",
	"compilers",
	"concurrency",
	"development-tools::build-utils",
]
description = "$RUSTC_WRAPPER tool to sandbox cargo builds and execute jobs remotely"
edition = "2021"
keywords = [
	"build",
	"buildkit",
	"docker",
	"DOCKER_HOST",
	"RUSTC_WRAPPER",
]
license = "MIT"
repository = "https://github.com/fenollp/rustcbuildx"

# [profile.release]
# codegen-units = 1
# Try tuning rustc codegen options to optimize for speed (suggest mold?)
# TODO: use the least amount of codegen units for best LTO
# https://doc.rust-lang.org/nightly/rustc/codegen-options/index.html#codegen-units
# https://doc.rust-lang.org/nightly/rustc/codegen-options/index.html#embed-bitcode
# https://doc.rust-lang.org/nightly/rustc/codegen-options/index.html#instrument-coverage
# https://doc.rust-lang.org/nightly/rustc/codegen-options/index.html#link-arg
# https://doc.rust-lang.org/nightly/rustc/codegen-options/index.html#linker

[dependencies]
anyhow = "1"
camino = "1"
env_logger = "0,>=0.11"
futures = "0.3"
log = "0,>=0.4"
mktemp = "0,>=0.5"
nutype = "0,>=0.4"
pretty_assertions = "1" # TODO: drop once !dbg
rustflags = "0,>=0.1" # TODO: drop once !dbg
serde = { version = "1", features = ["derive"] }
sha256 = "1"
szyk = "1"
tokio = { version = "1", features = ["macros", "io-util", "process", "rt-multi-thread", "time"] }
toml = "0,>=0.8"

[dev-dependencies]
assertx = { version = "1", features = ["logging"] }
