[package]
authors.workspace = true
categories.workspace = true
description = "Cargo plugin to sandbox, cache & remote exec cargo builds"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "cargo-green"
repository.workspace = true
version.workspace = true

[dependencies]
clap.workspace = true
