on: [push]
name: CLIs
jobs:


  meta-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./clis.sh | tee .github/workflows/clis.yml
    - run: git --no-pager diff --exit-code
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        check_together: 'yes'
        severity: error

  bin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/checkout@v4

    # Actually, the whole archives
    - name: Cache `cargo fetch`
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-deps-

    - name: Cache `cargo install`
      uses: actions/cache@v3
      with:
        path: ~/instmp
        key: ${{ runner.os }}-cargo-install-${{ hashFiles('**/Cargo.lock') }}-and-${{ hashFiles('src/**') }}
        restore-keys: |
          ${{ runner.os }}-cargo-install-${{ hashFiles('**/Cargo.lock') }}-and-
          ${{ runner.os }}-cargo-install-

    - name: Compile HEAD
      run: |
        CARGO_TARGET_DIR=~/instmp cargo install --force --path=$PWD

    - uses: actions/upload-artifact@v3
      with:
        name: bin-artifact
        path: ~/instmp/release/rustcbuildx

  cargo-audit_0-18-3:
    runs-on: ubuntu-latest
    needs: bin
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable


    - name: Retrieve saved bin
      uses: actions/download-artifact@v3
      with:
        name: bin-artifact
    - run: | # TODO: whence https://github.com/actions/download-artifact/issues/236
        chmod +x ./rustcbuildx
        ./rustcbuildx --version | grep rustcbuildx

    - name: cargo install net=ON cache=OFF remote=OFF
      run: |
        RUSTCBUILDX_DEBUG=1 \
        RUSTCBUILDX_LOG_PATH=./logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          CARGO_TARGET_DIR=~/instst cargo -vv install --force cargo-audit@0.18.3 --features=fix || \
            cat logs.txt

    - name: cargo install net=ON cache=ON remote=OFF
      run: |
        RUSTCBUILDX_DEBUG=1 \
        RUSTCBUILDX_LOG_PATH=./logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          CARGO_TARGET_DIR=~/instst cargo -vv install --force cargo-audit@0.18.3 --features=fix 2>&1 | tee _ || \
            cat logs.txt
        cat _ | grep Finished | grep 0...s
        cat _ | grep Fresh
        ! cat _ | grep Compiling
        ! cat _ | grep 'DEBUG|INFO|WARN|ERROR'

  cargo-deny_0-14-3:
    runs-on: ubuntu-latest
    needs: bin
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable


    - name: Retrieve saved bin
      uses: actions/download-artifact@v3
      with:
        name: bin-artifact
    - run: | # TODO: whence https://github.com/actions/download-artifact/issues/236
        chmod +x ./rustcbuildx
        ./rustcbuildx --version | grep rustcbuildx

    - name: cargo install net=ON cache=OFF remote=OFF
      run: |
        RUSTCBUILDX_DEBUG=1 \
        RUSTCBUILDX_LOG_PATH=./logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          CARGO_TARGET_DIR=~/instst cargo -vv install --force cargo-deny@0.14.3  || \
            cat logs.txt

    - name: cargo install net=ON cache=ON remote=OFF
      run: |
        RUSTCBUILDX_DEBUG=1 \
        RUSTCBUILDX_LOG_PATH=./logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          CARGO_TARGET_DIR=~/instst cargo -vv install --force cargo-deny@0.14.3  2>&1 | tee _ || \
            cat logs.txt
        cat _ | grep Finished | grep 0...s
        cat _ | grep Fresh
        ! cat _ | grep Compiling
        ! cat _ | grep 'DEBUG|INFO|WARN|ERROR'

  diesel_cli_2-1-1:
    runs-on: ubuntu-latest
    needs: bin
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable


    - name: Retrieve saved bin
      uses: actions/download-artifact@v3
      with:
        name: bin-artifact
    - run: | # TODO: whence https://github.com/actions/download-artifact/issues/236
        chmod +x ./rustcbuildx
        ./rustcbuildx --version | grep rustcbuildx

    - name: cargo install net=ON cache=OFF remote=OFF
      run: |
        RUSTCBUILDX_DEBUG=1 \
        RUSTCBUILDX_LOG_PATH=./logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          CARGO_TARGET_DIR=~/instst cargo -vv install --force diesel_cli@2.1.1 --no-default-features --features=postgres || \
            cat logs.txt

    - name: cargo install net=ON cache=ON remote=OFF
      run: |
        RUSTCBUILDX_DEBUG=1 \
        RUSTCBUILDX_LOG_PATH=./logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          CARGO_TARGET_DIR=~/instst cargo -vv install --force diesel_cli@2.1.1 --no-default-features --features=postgres 2>&1 | tee _ || \
            cat logs.txt
        cat _ | grep Finished | grep 0...s
        cat _ | grep Fresh
        ! cat _ | grep Compiling
        ! cat _ | grep 'DEBUG|INFO|WARN|ERROR'

  cargo-llvm-cov_0-5-36:
    runs-on: ubuntu-latest
    needs: bin
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: rustup component add llvm-tools-preview

    - name: Retrieve saved bin
      uses: actions/download-artifact@v3
      with:
        name: bin-artifact
    - run: | # TODO: whence https://github.com/actions/download-artifact/issues/236
        chmod +x ./rustcbuildx
        ./rustcbuildx --version | grep rustcbuildx

    - name: cargo install net=ON cache=OFF remote=OFF
      run: |
        RUSTCBUILDX_DEBUG=1 \
        RUSTCBUILDX_LOG_PATH=./logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          CARGO_TARGET_DIR=~/instst cargo -vv install --force cargo-llvm-cov@0.5.36  || \
            cat logs.txt

    - name: cargo install net=ON cache=ON remote=OFF
      run: |
        RUSTCBUILDX_DEBUG=1 \
        RUSTCBUILDX_LOG_PATH=./logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          CARGO_TARGET_DIR=~/instst cargo -vv install --force cargo-llvm-cov@0.5.36  2>&1 | tee _ || \
            cat logs.txt
        cat _ | grep Finished | grep 0...s
        cat _ | grep Fresh
        ! cat _ | grep Compiling
        ! cat _ | grep 'DEBUG|INFO|WARN|ERROR'

