on: [push]
name: self
jobs:


  bin:
    runs-on: ubuntu-latest
    steps:
    - run: docker buildx version
    - run: DOCKER_BUILDKIT=1 docker --help
    - run: docker buildx bake --help
    - run: docker buildx build --help

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/checkout@v4

    # Actually, the whole archives
    - name: Cache `cargo fetch`
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-deps-

    - name: Cache `cargo install`
      uses: actions/cache@v4
      with:
        path: ~/instmp
        key: ${{ runner.os }}-cargo-install-${{ hashFiles('**/Cargo.lock') }}-and-${{ hashFiles('src/**') }}
        restore-keys: |
          ${{ runner.os }}-cargo-install-${{ hashFiles('**/Cargo.lock') }}-and-
          ${{ runner.os }}-cargo-install-

    - name: Compile HEAD
      run: |
        CARGO_TARGET_DIR=~/instmp cargo install --locked --force --path=$PWD

    - uses: actions/upload-artifact@v3
      with:
        name: bin-artifact
        path: ~/instmp/release/rustcbuildx


  installs:
    runs-on: ubuntu-latest
    needs: bin
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Retrieve saved bin
      uses: actions/download-artifact@v3
      with:
        name: bin-artifact
    - run: | # TODO: whence https://github.com/actions/download-artifact/issues/236
        chmod +x ./rustcbuildx
        ./rustcbuildx --version | grep rustcbuildx

    - name: cargo install net=ON cache=OFF remote=OFF
      run: |
        RUSTCBUILDX_LOG=debug \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          CARGO_TARGET_DIR=~/instst cargo -vv install --jobs=1 --locked --force --path=.


  audits:
    runs-on: ubuntu-latest
    needs: bin
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Retrieve saved bin
      uses: actions/download-artifact@v3
      with:
        name: bin-artifact
    - run: | # TODO: whence https://github.com/actions/download-artifact/issues/236
        chmod +x ./rustcbuildx
        ./rustcbuildx --version | grep rustcbuildx

    # Actually, the whole archives
    - name: Cache `cargo fetch`
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-deps-

    - name: Cache `cargo install`
      uses: actions/cache@v4
      with:
        path: ~/cargo-audit
        key: ${{ runner.os }}-cargo-install-audit

    - name: Compile cargo-audit
      run: |
        CARGO_TARGET_DIR=~/cargo-audit cargo install --locked --force cargo-audit --features=fix

    - name: cargo audit net=ON cache=OFF remote=OFF
      run: |
        RUSTCBUILDX_LOG=debug \
        RUSTCBUILDX_LOG_PATH="$PWD"/logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          cargo -vv audit || \
            cat logs.txt


  builds:
    runs-on: ubuntu-latest
    needs: bin
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Cache `cargo fetch`
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-deps-

    - run: cargo fetch

    - name: Retrieve saved bin
      uses: actions/download-artifact@v3
      with:
        name: bin-artifact
    - run: | # TODO: whence https://github.com/actions/download-artifact/issues/236
        chmod +x ./rustcbuildx
        ./rustcbuildx --version | grep rustcbuildx

    - name: cargo build net=OFF cache=OFF remote=OFF
      run: |
        RUSTCBUILDX_LOG=debug \
        RUSTCBUILDX_LOG_PATH="$PWD"/logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          cargo -vv build --jobs=1 --all-targets --all-features --locked --frozen --offline

    - if: ${{ failure() || success() }}
      run: cat logs.txt && echo >logs.txt

    - name: Ensure running the same command twice without modifications does not recompile anything
      run: |
        RUSTCBUILDX_LOG=debug \
        RUSTCBUILDX_LOG_PATH="$PWD"/logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          cargo -vv build --jobs=1 --all-targets --all-features --locked --frozen --offline 2>&1 | tee _
        cat _ | grep Finished | grep 0...s
        cat _ | grep Fresh
        ! cat _ | grep Compiling
        ! cat _ | grep 'DEBUG|INFO|WARN|ERROR'

    - if: ${{ failure() || success() }}
      run: cat logs.txt && echo >logs.txt


  tests:
    runs-on: ubuntu-latest
    needs: bin
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Cache `cargo fetch`
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-deps-

    - run: cargo fetch

    - name: Retrieve saved bin
      uses: actions/download-artifact@v3
      with:
        name: bin-artifact
    - run: | # TODO: whence https://github.com/actions/download-artifact/issues/236
        chmod +x ./rustcbuildx
        ./rustcbuildx --version | grep rustcbuildx

    - name: cargo test net=OFF cache=OFF remote=OFF
      run: |
        RUSTCBUILDX_LOG=debug \
        RUSTCBUILDX_LOG_PATH="$PWD"/logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          cargo -vv test --jobs=1 --all-targets --all-features --locked --frozen --offline

    - if: ${{ failure() || success() }}
      run: cat logs.txt && echo >logs.txt

    - name: Ensure running the same command twice without modifications does not recompile anything
      run: |
        RUSTCBUILDX_LOG=debug \
        RUSTCBUILDX_LOG_PATH="$PWD"/logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          cargo -vv test --jobs=1 --all-targets --all-features --locked --frozen --offline 2>&1 | tee _
        cat _ | grep Finished | grep 0...s
        cat _ | grep Fresh
        ! cat _ | grep Compiling
        ! cat _ | grep 'DEBUG|INFO|WARN|ERROR'

    - if: ${{ failure() || success() }}
      run: cat logs.txt && echo >logs.txt


  checks:
    runs-on: ubuntu-latest
    needs: bin
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Cache `cargo fetch`
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-deps-

    - run: cargo fetch

    - name: Retrieve saved bin
      uses: actions/download-artifact@v3
      with:
        name: bin-artifact
    - run: | # TODO: whence https://github.com/actions/download-artifact/issues/236
        chmod +x ./rustcbuildx
        ./rustcbuildx --version | grep rustcbuildx

    - name: cargo check net=OFF cache=OFF remote=OFF
      run: |
        RUSTCBUILDX_LOG=debug \
        RUSTCBUILDX_LOG_PATH="$PWD"/logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          cargo -vv check --jobs=1 --all-targets --all-features --locked --frozen --offline

    - if: ${{ failure() || success() }}
      run: cat logs.txt && echo >logs.txt

    - name: Ensure running the same command twice without modifications does not recompile anything
      run: |
        RUSTCBUILDX_LOG=debug \
        RUSTCBUILDX_LOG_PATH="$PWD"/logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          cargo -vv check --jobs=1 --all-targets --all-features --locked --frozen --offline 2>&1 | tee _
        cat _ | grep Finished | grep 0...s
        cat _ | grep Fresh
        ! cat _ | grep Compiling
        ! cat _ | grep 'DEBUG|INFO|WARN|ERROR'

    - if: ${{ failure() || success() }}
      run: cat logs.txt && echo >logs.txt


  clippy:
    runs-on: ubuntu-latest
    needs: bin
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - run: rustup component add clippy

    - name: Cache `cargo fetch`
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cargo-deps-

    - run: cargo fetch

    - name: Retrieve saved bin
      uses: actions/download-artifact@v3
      with:
        name: bin-artifact
    - run: | # TODO: whence https://github.com/actions/download-artifact/issues/236
        chmod +x ./rustcbuildx
        ./rustcbuildx --version | grep rustcbuildx

    - name: cargo clippy net=OFF cache=OFF remote=OFF
      run: |
        RUSTCBUILDX_LOG=debug \
        RUSTCBUILDX_LOG_PATH="$PWD"/logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          cargo -vv clippy --jobs=1 --all-targets --all-features --locked --frozen --offline

    - if: ${{ failure() || success() }}
      run: cat logs.txt && echo >logs.txt

    - name: Ensure running the same command twice without modifications does not recompile anything
      run: |
        RUSTCBUILDX_LOG=debug \
        RUSTCBUILDX_LOG_PATH="$PWD"/logs.txt \
        RUSTC_WRAPPER="$PWD"/rustcbuildx \
          cargo -vv clippy --jobs=1 --all-targets --all-features --locked --frozen --offline 2>&1 | tee _
        cat _ | grep Finished | grep 0...s
        ! cat _ | grep 'Compiling|Compiling'
        ! cat _ | grep 'DEBUG|INFO|WARN|ERROR'

    - if: ${{ failure() || success() }}
      run: cat logs.txt && echo >logs.txt
